const SHOW_DELETE_MODAL = "modals/SHOW_DELETE_MODAL";
const SHOW_ADD_MODAL = "modals/SHOW_ADD_MODAL";
const SHOW_EDIT_MODAL = "modals/SHOW_EDIT_MODAL";
const CLOSE_ADD_EDIT = "modals/CLOSE_ADD_EDIT_MODAL";

export default {
  SHOW_DELETE_MODAL,
  SHOW_ADD_MODAL,
  SHOW_EDIT_MODAL,
  CLOSE_ADD_EDIT
};
