const FETCH_MOVIES = "movies/FETCH_MOVIES";
const FETCH_MOVIES_SUCCESS = "movies/FETCH_MOVIES_SUCCESS";
const FETCH_MOVIES_FAILD = "movies/FETCH_MOVIES_FAILD";

const LOAD_MOVIES = "movies/LOAD_MOVIES";
const LOAD_DETAILS = "movies/FETCH_DETAILS";


const SELECT_MOVIE = "movies/SELECT_MOVIE";
const ADD_MOVIE = "movies/ADD_MOVIE";
const EDIT_MOVIE = "movies/EDIT_MOVIE";
const DELETE_MOVIE = "movies/DELETE_MOVIE";


export default {
  FETCH_MOVIES,
  FETCH_MOVIES_SUCCESS,
  FETCH_MOVIES_FAILD,
  LOAD_MOVIES,
  LOAD_DETAILS,
  SELECT_MOVIE,
  ADD_MOVIE,
  EDIT_MOVIE,
  DELETE_MOVIE,
  
};
